# Generated by Django 4.1.1 on 2022-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_buy_cost_buy_quantity_buy_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='barcode',
            field=models.IntegerField(default=1),
        ),
    ]
